import { EventBusService, wrapHandler } from "@medusajs/medusa";
import geoip from "geoip-lite";
import { Router } from "express";
const router = Router();
router.get(
  "/",

  wrapHandler(async (req, res) => {
    try {
      const ip = req.headers["cf-connecting-ip"] || req.socket.remoteAddress;
      var geo = geoip.lookup(ip);
      res.status(200).json(geo);
    } catch (err) {
      res.sendStatus(400);
    }
  })
);

// router.post(
//   "/sendmail",

//   wrapHandler(async (req, res) => {
//     const sesService = req.scope.resolve("sesService");
//     // const eventBusService: EventBusService =
//     //   req.scope.resolve("eventBusService");
//     // eventBusService.emit("order.placed", {
//     //   id: "order_01H5VHTAKQ5MJNNVHDS21YAT9H",
//     //   no_notification: null,
//     // });
//     sesService
//       .sendEmail(
//         "order_placed",
//         "order@grin-global.com",
//         "lim.ac96@gmail.com",
//         {
//           object: "order",
//           id: "order_01H5VHTAKQ5MJNNVHDS21YAT9H",
//           customer: {
//             id: "cus_01H36S4Y56PWB5BMQN581R6Y8G",
//             created_at: "2023-06-18T08:15:08.431Z",
//             updated_at: "2023-07-05T15:17:33.178Z",
//             deleted_at: null,
//             email: "lim.ac96@gmail.com",
//             first_name: null,
//             last_name: null,
//             billing_address_id: null,
//             phone: null,
//             has_account: false,
//             metadata: { stripe_id: "cus_OCxNrSSRiHHIDq" },
//           },
//           billing_address: {
//             id: "addr_01H5VHT6JN987CSCXHT3XM7EHC",
//             created_at: "2023-07-21T06:22:23.270Z",
//             updated_at: "2023-07-21T06:22:23.270Z",
//             deleted_at: null,
//             customer_id: null,
//             company: "",
//             first_name: "Lim",
//             last_name: "Chong",
//             address_1: "63 JALAN KULIM, TAMAN BATU PAHAT",
//             address_2: "TAMAN BATU PAHAT",
//             city: "Batu Pahat",
//             country_code: "my",
//             province: "JOHOR",
//             postal_code: "83000",
//             phone: "0142746480",
//             metadata: null,
//           },
//           shipping_address: {
//             id: "addr_01H5VHT6JNFT8ZYM6ESE4XSWCY",
//             created_at: "2023-07-21T06:22:23.270Z",
//             updated_at: "2023-07-21T06:22:23.270Z",
//             deleted_at: null,
//             customer_id: null,
//             company: "",
//             first_name: "Lim",
//             last_name: "Chong",
//             address_1: "63 JALAN KULIM, TAMAN BATU PAHAT",
//             address_2: "TAMAN BATU PAHAT",
//             city: "Batu Pahat",
//             country_code: "my",
//             province: "JOHOR",
//             postal_code: "83000",
//             phone: "0142746480",
//             metadata: null,
//           },
//           discounts: [],
//           shipping_methods: [
//             {
//               id: "sm_01H5VHT7Z2BR8YKPQHJDBGT79Z",
//               shipping_option_id: "so_01H36S3F3A8M3AHCSSQ2RG49ZZ",
//               order_id: "order_01H5VHTAKQ5MJNNVHDS21YAT9H",
//               claim_order_id: null,
//               cart_id: "cart_01H5VH9GQYG6X65BX80M3YKPD1",
//               swap_id: null,
//               return_id: null,
//               price: 2000,
//               data: {},
//               includes_tax: false,
//               shipping_option: {
//                 id: "so_01H36S3F3A8M3AHCSSQ2RG49ZZ",
//                 created_at: "2023-06-18T08:14:20.263Z",
//                 updated_at: "2023-06-18T08:16:34.515Z",
//                 deleted_at: null,
//                 name: "J&T",
//                 region_id: "reg_01H31MKKT50R2YC2M4E4PRDXB8",
//                 profile_id: "sp_01H2YVVYTZMSPP6R9PQ7KAW3N7",
//                 provider_id: "manual",
//                 price_type: "flat_rate",
//                 amount: 2000,
//                 is_return: false,
//                 admin_only: false,
//                 data: { id: "manual-fulfillment" },
//                 metadata: null,
//                 includes_tax: false,
//               },
//               tax_lines: [
//                 {
//                   id: "smtl_01H5VHTAHBH71S73C6FJABVEFS",
//                   created_at: "2023-07-21T06:22:27.356Z",
//                   updated_at: "2023-07-21T06:22:27.414Z",
//                   rate: 0,
//                   name: "default",
//                   code: "default",
//                   metadata: null,
//                   shipping_method_id: "sm_01H5VHT7Z2BR8YKPQHJDBGT79Z",
//                 },
//               ],
//             },
//           ],
//           payments: [
//             {
//               id: "pay_01H5VHTAJ8JJ04SPYDK4B0N1HJ",
//               created_at: "2023-07-21T06:22:27.376Z",
//               updated_at: "2023-07-21T06:22:27.414Z",
//               swap_id: null,
//               cart_id: "cart_01H5VH9GQYG6X65BX80M3YKPD1",
//               order_id: "order_01H5VHTAKQ5MJNNVHDS21YAT9H",
//               amount: 15090,
//               currency_code: "myr",
//               amount_refunded: 0,
//               provider_id: "manual",
//               data: { status: "authorized" },
//               captured_at: null,
//               canceled_at: null,
//               metadata: null,
//               idempotency_key: null,
//             },
//           ],
//           fulfillments: [],
//           returns: [],
//           gift_cards: [],
//           gift_card_transactions: [],
//           items: [
//             {
//               id: "item_01H5VHT1HX30ME010JW3CK2GY1",
//               created_at: "2023-07-21T06:22:18.141Z",
//               updated_at: "2023-07-21T06:22:27.414Z",
//               cart_id: "cart_01H5VH9GQYG6X65BX80M3YKPD1",
//               order_id: "order_01H5VHTAKQ5MJNNVHDS21YAT9H",
//               swap_id: null,
//               claim_order_id: null,
//               original_item_id: null,
//               order_edit_id: null,
//               title: "Shampoo",
//               description: "1000g",
//               thumbnail:
//                 "http://localhost:9000/uploads\\Screen Shot 2023-06-28 at 18.24.25-1688981333707.png",
//               is_return: false,
//               is_giftcard: false,
//               should_merge: true,
//               allow_discounts: true,
//               has_shipping: true,
//               unit_price: 13090,
//               variant_id: "variant_01H54TEZSE75T3YNEAC03N0NY9",
//               quantity: 1,
//               fulfilled_quantity: null,
//               returned_quantity: null,
//               shipped_quantity: null,
//               metadata: {},
//               includes_tax: false,
//               tax_lines: [
//                 {
//                   id: "litl_01H5VHTAHATDQ7YB3P3V24YK6A",
//                   created_at: "2023-07-21T06:22:27.356Z",
//                   updated_at: "2023-07-21T06:22:27.414Z",
//                   rate: 0,
//                   name: "default",
//                   code: "default",
//                   metadata: null,
//                   item_id: "item_01H5VHT1HX30ME010JW3CK2GY1",
//                 },
//               ],
//               adjustments: [],
//               variant: {
//                 id: "variant_01H54TEZSE75T3YNEAC03N0NY9",
//                 created_at: "2023-07-12T10:31:01.158Z",
//                 updated_at: "2023-07-21T06:22:27.414Z",
//                 deleted_at: null,
//                 title: "1000g",
//                 product_id: "prod_01H4ZJ3947P97J1AMBEPVXA1C2",
//                 sku: null,
//                 barcode: null,
//                 ean: null,
//                 upc: null,
//                 variant_rank: 1,
//                 inventory_quantity: 49,
//                 allow_backorder: false,
//                 manage_inventory: false,
//                 hs_code: null,
//                 origin_country: null,
//                 mid_code: null,
//                 material: null,
//                 weight: null,
//                 length: null,
//                 height: null,
//                 width: null,
//                 metadata: {},
//                 product: {
//                   id: "prod_01H4ZJ3947P97J1AMBEPVXA1C2",
//                   created_at: "2023-07-10T09:28:36.738Z",
//                   updated_at: "2023-07-10T09:28:53.729Z",
//                   deleted_at: null,
//                   title: "Shampoo",
//                   subtitle: null,
//                   description: null,
//                   handle: "shampoo",
//                   is_giftcard: false,
//                   status: "published",
//                   thumbnail:
//                     "http://localhost:9000/uploads\\Screen Shot 2023-06-28 at 18.24.25-1688981333707.png",
//                   profile_id: "sp_01H2YVVYTZMSPP6R9PQ7KAW3N7",
//                   weight: null,
//                   length: null,
//                   height: null,
//                   width: null,
//                   hs_code: null,
//                   origin_country: null,
//                   mid_code: null,
//                   material: null,
//                   collection_id: null,
//                   type_id: null,
//                   discountable: true,
//                   external_id: null,
//                   metadata: null,
//                 },
//               },
//               subtotal: 13090,
//               discount_total: 0,
//               total: 13090,
//               original_total: 13090,
//               original_tax_total: 0,
//               tax_total: 0,
//               raw_discount_total: 0,
//               totals: {
//                 unit_price: 13090,
//                 quantity: 1,
//                 subtotal: 13090,
//                 discount_total: 0,
//                 total: 13090,
//                 original_total: 13090,
//                 original_tax_total: 0,
//                 tax_total: 0,
//                 tax_lines: [
//                   {
//                     id: "litl_01H5VHTAHATDQ7YB3P3V24YK6A",
//                     created_at: "2023-07-21T06:22:27.356Z",
//                     updated_at: "2023-07-21T06:22:27.414Z",
//                     rate: 0,
//                     name: "default",
//                     code: "default",
//                     metadata: null,
//                     item_id: "item_01H5VHT1HX30ME010JW3CK2GY1",
//                   },
//                 ],
//                 raw_discount_total: 0,
//               },
//               discounted_price: "130.90 MYR",
//               price: "130.90 MYR",
//             },
//           ],
//           swaps: [],
//           claims: [],
//           refunds: [],
//           region: {
//             id: "reg_01H31MKKT50R2YC2M4E4PRDXB8",
//             created_at: "2023-06-16T08:19:34.327Z",
//             updated_at: "2023-06-20T14:05:28.203Z",
//             deleted_at: null,
//             name: "Malaysia",
//             currency_code: "myr",
//             tax_rate: 0,
//             tax_code: null,
//             gift_cards_taxable: true,
//             automatic_taxes: true,
//             tax_provider_id: null,
//             metadata: {},
//             includes_tax: false,
//           },
//           created_at: "2023-07-21T06:22:27.414Z",
//           updated_at: "2023-07-21T06:22:27.414Z",
//           status: "pending",
//           fulfillment_status: "not_fulfilled",
//           payment_status: "awaiting",
//           display_id: 27,
//           cart_id: "cart_01H5VH9GQYG6X65BX80M3YKPD1",
//           customer_id: "cus_01H36S4Y56PWB5BMQN581R6Y8G",
//           email: "lim.ac96@gmail.com",
//           billing_address_id: "addr_01H5VHT6JN987CSCXHT3XM7EHC",
//           shipping_address_id: "addr_01H5VHT6JNFT8ZYM6ESE4XSWCY",
//           region_id: "reg_01H31MKKT50R2YC2M4E4PRDXB8",
//           currency_code: "myr",
//           tax_rate: null,
//           draft_order_id: null,
//           canceled_at: null,
//           metadata: {},
//           no_notification: null,
//           idempotency_key: null,
//           external_id: null,
//           sales_channel_id: "sc_01H2YVVYVF616VG7Q7B8XST84G",
//           shipping_total: "20.00 MYR",
//           discount_total: "0.00 MYR",
//           tax_total: "0.00 MYR",
//           refunded_total: 0,
//           gift_card_total: "0.00 MYR",
//           gift_card_tax_total: 0,
//           subtotal: "130.90 MYR",
//           total: "150.90 MYR",
//           locale: null,
//           has_discounts: 0,
//           has_gift_cards: 0,
//           date: "Fri Jul 21 2023",
//           subtotal_ex_tax: "130.90 MYR",
//         }
//       )
//       .then((result) => {
//         return res.send(result);
//       });
//   })
// );

export default router;
